# -*- coding: utf-8 -*-
"""traffic_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soG_s-9mahdThmANVpm2uHTtTQPMzO38
"""


from ultralytics import YOLO
import cv2
# import easyocr
from paddleocr import PaddleOCR
import pandas as pd
from datetime import datetime
from collections import deque

vehicle_model = YOLO("yolov8n.pt")
plate_model = YOLO("license_plate_detector.pt")

# reader = easyocr.Reader(['en'])
ocr_engine = PaddleOCR(use_angle_cls=True, lang='en')


video_path = "videos/uploaded_video.mp4"

cap = cv2.VideoCapture(video_path)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

out = cv2.VideoWriter(
    "outputs/_raw_output.mp4",
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (width, height)
)

LINE_Y = 400
SPEED_LIMIT=60

# Re-measure these values for each new camera angle/video; this calibration is scene-specific.
PIXEL_DISTANCE_REFERENCE = 200
REAL_WORLD_DISTANCE_METERS = 10
METERS_PER_PIXEL = REAL_WORLD_DISTANCE_METERS / PIXEL_DISTANCE_REFERENCE


vehicle_positions = {}

vehicle_paths  = {}

previous_centers={}

centroid_buffers = {}

crossed_ids = set()

records = []

display_id_counter = 0
frame_index = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    frame_index += 1
    if frame_index % 30 == 0:
        print(f"Processed frame {frame_index}/{total_frames}")

    detect_frame = cv2.resize(frame, None, fx=0.25, fy=0.25, interpolation=cv2.INTER_AREA)

    # TRACK VEHICLES
    results = vehicle_model.track(
        detect_frame,
        persist=True,
        tracker="bytetrack.yaml",
        classes=[2, 3, 5, 7],
        conf=0.4,
        verbose=False
    )

    annotated_frame = frame.copy()

    cv2.line(
        annotated_frame,
        (0, LINE_Y),
        (width, LINE_Y),
        (0, 255, 0),
        3
    )

    if results[0].boxes.id is not None:

        boxes = results[0].boxes.xyxy.cpu().numpy()
        ids = results[0].boxes.id.cpu().numpy()

        classes = results[0].boxes.cls.cpu().numpy()
        class_names = vehicle_model.names


        for i, (box, track_id) in enumerate(zip(boxes, ids)):

            x1,y1,x2,y2 = map(int, box)
            x1, y1, x2, y2 = x1 * 4, y1 * 4, x2 * 4, y2 * 4

            cls_id = int(classes[i])
            vehicle_type = class_names[cls_id]

            center_x=int((x1 + x2) / 2)
            center_y=int((y1 + y2) / 2)

            if track_id not in centroid_buffers:
                centroid_buffers[track_id] = deque(maxlen=8)

            centroid_buffers[track_id].append((center_x, center_y))

            smoothed_center_x = int(
                sum(point[0] for point in centroid_buffers[track_id]) / len(centroid_buffers[track_id])
            )
            smoothed_center_y = int(
                sum(point[1] for point in centroid_buffers[track_id]) / len(centroid_buffers[track_id])
            )

            center_x = smoothed_center_x
            center_y = smoothed_center_y

            speed=0
            violation="Normal"
            previous_y=vehicle_positions.get(track_id, center_y)

            vehicle_positions[track_id] = center_y

            if len(centroid_buffers[track_id]) >= 3 and track_id in previous_centers:
                prev_center_x, prev_center_y = previous_centers[track_id]

                dx=center_x - prev_center_x
                dy=center_y - prev_center_y

                pixel_distance=(dx**2 + dy**2)**0.5

                elapsed_time_seconds = 1 / fps
                distance_meters = pixel_distance * METERS_PER_PIXEL
                speed_mps = distance_meters / elapsed_time_seconds
                speed = speed_mps * 3.6

                if speed > SPEED_LIMIT:
                    violation="Overspeeding"

            previous_centers[track_id]=(center_x, center_y)

            if len(centroid_buffers[track_id]) >= 3:
                if track_id not in vehicle_paths:
                    vehicle_paths[track_id] = []

                vehicle_paths[track_id].append((center_x, center_y))

                for j in range(1, len(vehicle_paths[track_id])):

                    cv2.line(
                        annotated_frame,
                        vehicle_paths[track_id][j - 1],
                        vehicle_paths[track_id][j],
                        (255, 0, 0),
                        2
                            )

            color = (0, 255, 255)

            if violation == "Overspeeding":
                color = (0, 0, 255)

            cv2.rectangle(
                        annotated_frame,
                        (x1, y1),
                        (x2, y2),
                        color,
                        2
                        )

            cv2.putText(
                        annotated_frame,
                        f"{vehicle_type} {int(track_id)}",
                        (x1, y1 - 35),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        color,
                        2
                        )

            cv2.putText(
                        annotated_frame,
                        f"{int(speed)} km/h | {violation}",
                        (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        color,
                        2
                        )
                
            if previous_y < LINE_Y and center_y >= LINE_Y:

                if track_id not in crossed_ids:

                    crossed_ids.add(track_id)

                    vehicle_crop = frame[y1:y2, x1:x2]
                    plate_text = "UNKNOWN"
                    plate_results = plate_model(vehicle_crop, conf=0.3, verbose=False)
                    plate_boxes = plate_results[0].boxes.xyxy.cpu().numpy()

                    if len(plate_boxes) == 0:
                        plate_text = "No plate detected"
                    else:
                        ocr_texts = []

                        for plate_box in plate_boxes:
                            px1, py1, px2, py2 = map(int, plate_box)
                            plate_crop = vehicle_crop[py1:py2, px1:px2]

                            if plate_crop.size == 0:
                                continue

                            gray = cv2.cvtColor(plate_crop, cv2.COLOR_BGR2GRAY)
                            upscaled = cv2.resize(gray, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
                            thresh = cv2.adaptiveThreshold(
                                upscaled, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2
                            )
                            ocr_result = ocr_engine.ocr(thresh, cls=True)

                            if ocr_result and ocr_result[0]:

                                for line in ocr_result[0]:
                                    text, confidence = line[1]

                                    if confidence >= 0.5:
                                        ocr_texts.append(text)

                        if len(ocr_texts) > 0:
                            plate_text = max(ocr_texts, key=len)


                    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    print(f"Vehicle {track_id} | Plate: {plate_text} | Time: {timestamp}")

                    display_id_counter += 1
                    records.append({
                        "Display_ID": display_id_counter,
                        "Vehicle_ID": int(track_id),
                        "Vehicle_Type": vehicle_type,
                        "Speed": int(speed),
                        "Violation": violation,
                        "Plate_Number": plate_text,
                        "Timestamp": timestamp
                    })

    out.write(annotated_frame)

cap.release()
out.release()

import subprocess
try:
    subprocess.run([
        "ffmpeg", "-y", "-i", "outputs/_raw_output.mp4",
        "-vcodec", "libx264", "-pix_fmt", "yuv420p",
        "outputs/final_output.mp4"
    ], check=True)
except Exception as e:
    print(f"ffmpeg re-encode failed: {e}")


df = pd.DataFrame(records)
df.to_csv("outputs/vehicle_records.csv", index=False)
print("FINAL PROCESS COMPLETE")


